### ISSUE TITLE
Modrinth page is outdated!

### ISSUE THREAD

**Issue by syrupderg** [50ap5ud5/BoatItemView#11]
[Modrinth page](https://modrinth.com/mod/boat-item-view) is outdated for 8 months!
![image](https://github.com/50ap5ud5/BoatItemView/assets/67545942/a3843dac-6c23-4cc1-b851-b79bb573b68f)

**Comment by RubixDev** [comment]
The latest version on modrinth is the same as the latest on CurseForge and works on all 1.20.x versions. The Modrinth page should have that info updated however to make this mod easier to find and add in the Modrinth app on 1.20.4 for example, the CurseForge page already did this

**Comment by syrupderg** [comment]
> The latest version on modrinth is the same as the latest on CurseForge and works on all 1.20.x versions. The Modrinth page should have that info updated however to make this mod easier to find and add in the Modrinth app on 1.20.4 for example, the CurseForge page already did this

It still shows only up to 1.20.2, on curseforge its up to 1.20.4 version 
![image](https://github.com/50ap5ud5/BoatItemView/assets/67545942/65abfad2-fdb7-4eb1-a60e-73473df8b5f2)

**Comment by RubixDev** [comment]
> It still shows only up to 1.20.2, on curseforge its up to 1.20.4 version

That's exactly what I'm saying with my second sentence. While the latest version on Modrinth works with 1.20.4, it doesn't say that it does, and the Mod author should update that.

**Comment by 50ap5ud5** [comment]
Thank you for point this out. I have updated the Modrinth version range to reflect its compatibility with 1.20.4.
