### ISSUE TITLE
modrinth version range is wrong

### ISSUE THREAD

**Issue by SettingDust** [50ap5ud5/BoatItemView#4]
https://modrinth.com/mod/boat-item-view/version/1.18-0.0.3-fabric
Only support 1.18

**Comment by 50ap5ud5** [comment]
Hello, can you please clarify what do you mean "by only support 1.18"? Does it not work with 1.18.1 and 1.18.2?

**Comment by SettingDust** [comment]
> Hello, can you please clarify what do you mean "by only support 1.18"? Does it not work with 1.18.1 and 1.18.2?

It works. But not mark as support

**Comment by 50ap5ud5** [comment]
I see, thanks for letting me know. The supported version range has now been updated to include 1.18.1 and 1.18.2.
